### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by ComputerMaverick69** [Flutterwave/flutter_standard#11]
```
MissingPluginException (MissingPluginException(No implementation found for method open on channel com.pichillilorenzo/flutter_inappbrowser))
```

When i initialize the package and draw the UI as per the docs, it shows only a make payment button without any other option on whether to pay using a card, ussd or anything else. Upon clicking this button the above error is triggered.

![Simulator Screen Shot - iPhone 13 Pro - 2022-04-15 at 23 30 46](https://user-images.githubusercontent.com/43058711/163649589-bda2d201-a15e-4d69-9b82-ca936923b663.png)

**Comment by ComputerMaverick69** [comment]
The screen above is the screen generated by the plugin itself. The only customisations are the colors and icons on the app bar.

**Comment by Mohit-Joshi-dev** [comment]
Hii,
This error can be resolved with 2 solution,

- Try `flutter clean` and then run the app.
- Check if all the implementation are correctly done, for example, if the package needs some permission or something else.

And for the last one suggestion from my side please don't use this `flutter_inappbrowser` package it is DISCONTINUED, you can use `flutter_inappwebview`.

[https://pub.dev/packages/flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview)

**Comment by ComputerMaverick69** [comment]
I was able to get rid of this error using the flutter clean.
