### ISSUE TITLE
Can't disable Barter Payment Option

### ISSUE THREAD

**Issue by SR-INGENIOUSMINDSLAB** [Flutterwave/flutter_standard#6]
Hi,

I'm using this paymentOption for enable only mobilemoneyghana but in payment screen i saw Barter,card Payment also how can i disable it? is there any way to exclude it?

`paymentOptions: "mobilemoneyghana",`

**Comment by Corvus97** [comment]
Hello @SR-INGENIOUSMINDSLAB 👋🏽 ,

Thanks for sharing this experience with the team. You should disable dashboard payment options in your account settings.

This would allow only Mobile money to be displayed on the payment modal. If you have any follow up questions, you can send us a message on [Slack](https://bit.ly/34Vkzcg).
